#!/usr/bin/env python3
"""Generate a per-machine results page (machines/<id>.md) from results/*.csv.

Keeps the README focused on the *process*; each machine's numbers live on its own
page, built from the CSV rows tagged with its machine_id. Re-run any time after a
sweep to refresh a machine's page:

  python3 report.py                 # this machine (auto-detected id)
  python3 report.py --machine <id>  # a specific machine
  python3 report.py --all           # every machine present in the CSV
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys

import machine

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results", "results.csv")
THROUGHPUT = os.path.join(HERE, "results", "throughput.csv")
REGISTRY_DIR = os.path.join(HERE, "machines")


def _read_csv(path: str) -> list[dict]:
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def _specs_block(mid: str) -> str:
    path = os.path.join(REGISTRY_DIR, mid + ".json")
    if not os.path.exists(path):
        return "_No registry entry found._\n"
    with open(path, encoding="utf-8") as f:
        reg = json.load(f)
    s = reg.get("specs", {})
    rows = [
        ("CPU", s.get("cpu")),
        ("Cores", f"{s.get('cpu_cores_physical')} physical / "
                  f"{s.get('cpu_cores_logical')} logical"),
        ("RAM", f"{s.get('ram_gb')} GB" + (f" — {s['ram_note']}" if s.get("ram_note") else "")),
        ("GPU", s.get("gpu_summary")),
        ("OS", s.get("os")),
    ]
    out = ["| | |", "|---|---|"]
    out += [f"| {k} | {v} |" for k, v in rows if v not in (None, "None")]
    if reg.get("note"):
        out.append("")
        out.append(f"> {reg['note']}")
    return "\n".join(out) + "\n"


def _decode_table(rows: list[dict]) -> str:
    dec = [r for r in rows if r.get("mode") == "decode" and _num(r.get("tg_tok_s"))]
    dec.sort(key=lambda r: _num(r["tg_tok_s"]), reverse=True)
    if not dec:
        return "_No decode runs recorded._\n"
    head = ("| tg tok/s | quant | ctx | par | mtp | flash | kv | threads | "
            "accept | label |")
    sep = "|---:|---|---:|---:|---|---|---|---:|---:|---|"
    lines = [head, sep]
    for r in dec:
        acc = r.get("accept_rate")
        acc = f"{float(acc):.2f}" if _num(acc) else "—"
        lines.append(
            f"| **{_num(r['tg_tok_s']):.1f}** | {r['quant']} | {r['ctx']} | "
            f"{r['parallel']} | {r['mtp']} | {r['flash']} | {r['kv_quant']} | "
            f"{r['threads']} | {acc} | {r['label']} |")
    return "\n".join(lines) + "\n"


def _throughput_table(rows: list[dict]) -> str:
    if not rows:
        return ""
    # Report decode tok/s (same metric as the single-stream table above) so it's
    # apples-to-apples: total = all streams combined, per-stream = what each user sees.
    # (total = per-stream decode rate x concurrency.)
    lines = ["", "## Concurrency / throughput",
             "",
             "Both columns are **decode tok/s** — same metric as the single-stream table. "
             "*Total* is the combined generation rate across all streams; *per stream* is what "
             "each concurrent user experiences (at 1 stream they're equal).",
             "",
             "| streams | decode tok/s (total) | decode tok/s (per stream) | quant | ctx | mtp | label |",
             "|---:|---:|---:|---|---:|---|---|"]
    rows.sort(key=lambda r: (r.get("quant", ""), r.get("mtp", ""),
                             _num(r.get("concurrency")) or 0))
    for r in rows:
        per = _num(r.get("mean_stream_tok_s"))
        conc = int(_num(r.get("concurrency")) or 1)
        total = per * conc if per is not None else None
        lines.append(
            f"| {conc} | {total:.0f} | {per:.1f} | {r['quant']} | {r['ctx']} | "
            f"{r.get('mtp','')} | {r['label']} |")
    return "\n".join(lines) + "\n"


def build_page(mid: str) -> str:
    dec_rows = [r for r in _read_csv(RESULTS) if r.get("machine_id") == mid]
    tput_rows = [r for r in _read_csv(THROUGHPUT) if r.get("machine_id") == mid]
    parts = [
        f"# Results — `{mid}`",
        "",
        "Auto-generated by `report.py` from `results/results.csv`. Do not hand-edit; "
        "re-run `python3 report.py` after a sweep. See the top-level `README.md` for "
        "the methodology.",
        "",
        "## Machine",
        "",
        _specs_block(mid),
        "## Single-stream decode (sorted fastest first)",
        "",
        _decode_table(dec_rows),
    ]
    tput = _throughput_table(tput_rows)
    if tput:
        parts.append(tput)
    # Hand-written analysis in machines/<id>.notes.md survives regeneration and is
    # appended verbatim — so a machine can keep authored prose alongside auto tables.
    notes = os.path.join(REGISTRY_DIR, mid + ".notes.md")
    if os.path.exists(notes):
        with open(notes, encoding="utf-8") as f:
            parts.append("\n## Notes\n\n" + f.read().strip())
    return "\n".join(parts).rstrip() + "\n"


def write_page(mid: str) -> str:
    machine.ensure_registered(mid) if mid == machine.get_machine_id() else None
    os.makedirs(REGISTRY_DIR, exist_ok=True)
    path = os.path.join(REGISTRY_DIR, mid + ".md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(build_page(mid))
    print(f"[report] wrote {path}", file=sys.stderr)
    return path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--machine", default=None, help="machine id (default: this machine)")
    p.add_argument("--all", action="store_true",
                   help="regenerate a page for every machine_id in the CSV")
    a = p.parse_args()

    if a.all:
        ids = sorted({r["machine_id"] for r in _read_csv(RESULTS) if r.get("machine_id")})
        for mid in ids:
            write_page(mid)
    else:
        write_page(a.machine or machine.get_machine_id())
    return 0


if __name__ == "__main__":
    sys.exit(main())
