#!/usr/bin/env python3
"""Generate a per-machine results page (machines/<id>.md) from results/*.csv.

Keeps the README focused on the *process*; each machine's numbers live on its own
page, built from the CSV rows tagged with its machine_id. Re-run any time after a
sweep to refresh a machine's page:

  python3 report.py                 # this machine (auto-detected id)
  python3 report.py --machine <id>  # a specific machine
  python3 report.py --all           # every machine present in the CSV
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys

import machine

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results", "results.csv")
REGISTRY_DIR = os.path.join(HERE, "machines")


def _read_csv(path: str) -> list[dict]:
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def _specs_block(mid: str) -> str:
    path = os.path.join(REGISTRY_DIR, mid + ".json")
    if not os.path.exists(path):
        return "_No registry entry found._\n"
    with open(path, encoding="utf-8") as f:
        reg = json.load(f)
    s = reg.get("specs", {})
    rows = [
        ("CPU", s.get("cpu")),
        ("Cores", f"{s.get('cpu_cores_physical')} physical / "
                  f"{s.get('cpu_cores_logical')} logical"),
        ("RAM", f"{s.get('ram_gb')} GB" + (f" — {s['ram_note']}" if s.get("ram_note") else "")),
        ("GPU", s.get("gpu_summary")),
        ("OS", s.get("os")),
    ]
    out = ["| | |", "|---|---|"]
    out += [f"| {k} | {v} |" for k, v in rows if v not in (None, "None")]
    if reg.get("note"):
        out.append("")
        out.append(f"> {reg['note']}")
    return "\n".join(out) + "\n"


def _decode_table(rows: list[dict]) -> str:
    dec = [r for r in rows if r.get("mode") == "decode" and _num(r.get("tg_tok_s"))]
    if not dec:
        return "_No decode runs recorded._\n"
    # Group by model, then quant, then streams — every row is self-describing.
    # Both tok/s columns are decode; agg = per-stream x streams (equal at 1 stream).
    dec.sort(key=lambda r: (r.get("model", ""), r.get("quant", ""),
                            _num(r.get("concurrency")) or 1))
    head = ("| model | quant | ctx | streams | decode/stream tok/s | "
            "decode agg tok/s | mtp | accept | label |")
    sep = "|---|---|---:|---:|---:|---:|---|---:|---|"
    lines = [head, sep]
    for r in dec:
        acc = r.get("accept_rate")
        acc = f"{float(acc):.2f}" if _num(acc) else "—"
        conc = int(_num(r.get("concurrency")) or 1)
        per = _num(r.get("tg_tok_s"))
        agg = _num(r.get("tg_tok_s_agg")) or (per * conc if per else None)
        lines.append(
            f"| {r.get('model','')} | {r['quant']} | {r['ctx']} | {conc} | "
            f"{per:.1f} | {agg:.0f} | {r['mtp']} | {acc} | {r['label']} |")
    return "\n".join(lines) + "\n"


def _prefill_table(rows: list[dict]) -> str:
    pf = [r for r in rows if r.get("mode") == "prefill" and _num(r.get("pp_tok_s"))]
    if not pf:
        return ""
    pf.sort(key=lambda r: (r.get("model", ""), r.get("quant", "")))
    lines = ["", "## Prefill (prompt ingest)", "",
             "| model | quant | ctx | pp tok/s | ttft s | label |",
             "|---|---|---:|---:|---:|---|"]
    for r in pf:
        ttft = _num(r.get("ttft_s"))
        lines.append(
            f"| {r.get('model','')} | {r['quant']} | {r['ctx']} | "
            f"{_num(r['pp_tok_s']):.0f} | {ttft:.2f} | {r['label']} |"
            if ttft is not None else
            f"| {r.get('model','')} | {r['quant']} | {r['ctx']} | "
            f"{_num(r['pp_tok_s']):.0f} | — | {r['label']} |")
    return "\n".join(lines) + "\n"


def build_page(mid: str) -> str:
    dec_rows = [r for r in _read_csv(RESULTS) if r.get("machine_id") == mid]
    parts = [
        f"# Results — `{mid}`",
        "",
        "Auto-generated by `report.py` from `results/results.csv`. Do not hand-edit; "
        "re-run `python3 report.py` after a sweep. See the top-level `README.md` for "
        "the methodology.",
        "",
        "## Machine",
        "",
        _specs_block(mid),
        "## Decode",
        "",
        "All tok/s are **decode** (generation) rate. `streams` = concurrent requests "
        "(1 = single-stream); *decode/stream* is what one user sees, *decode agg* is the "
        "combined rate across all streams (equal at 1 stream).",
        "",
        _decode_table(dec_rows),
    ]
    prefill = _prefill_table(dec_rows)
    if prefill:
        parts.append(prefill)
    # Hand-written analysis in machines/<id>.notes.md survives regeneration and is
    # appended verbatim — so a machine can keep authored prose alongside auto tables.
    notes = os.path.join(REGISTRY_DIR, mid + ".notes.md")
    if os.path.exists(notes):
        with open(notes, encoding="utf-8") as f:
            parts.append("\n## Notes\n\n" + f.read().strip())
    return "\n".join(parts).rstrip() + "\n"


def write_page(mid: str) -> str:
    machine.ensure_registered(mid) if mid == machine.get_machine_id() else None
    os.makedirs(REGISTRY_DIR, exist_ok=True)
    path = os.path.join(REGISTRY_DIR, mid + ".md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(build_page(mid))
    print(f"[report] wrote {path}", file=sys.stderr)
    return path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--machine", default=None, help="machine id (default: this machine)")
    p.add_argument("--all", action="store_true",
                   help="regenerate a page for every machine_id in the CSV")
    a = p.parse_args()

    if a.all:
        ids = sorted({r["machine_id"] for r in _read_csv(RESULTS) if r.get("machine_id")})
        for mid in ids:
            write_page(mid)
    else:
        write_page(a.machine or machine.get_machine_id())
    return 0


if __name__ == "__main__":
    sys.exit(main())
